version: '3.8'

services:
  # PHP Service
  lande-task:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: lande-task
    volumes:
      - .:/var/www/html
      - ./Docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/html
    networks:
      - app_network
    depends_on:
      - mariadb
    env_file:
      - .env

  # Nginx Service
  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html  # Mount Laravel app
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"   # Expose HTTP port for serving the app
    networks:
      - app_network
    depends_on:
      - lande-task

  # MySQL/MariaDB Service
  mariadb:
    image: mariadb:10
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MARIADB_HOST: '${DB_HOST}'
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT:-3306}:3306'
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
